### ISSUE TITLE
Publish to ros.org

### ISSUE THREAD

**Issue by tomlogan501** [CentraleNantesRobotics/ping360_sonar#17]
Just a reminder to publish the package to the ROS community

> https://www.ros.org/browse/list.php

**Comment by tomlogan501** [comment]
About Coding conventions, ROS provides a [linter](http://wiki.ros.org/roslint) for python, it can also automatically format the code.

**Comment by Stormiix** [comment]
I'm having a bit of an issue with roslint at the moment, but will take a look at it later on and try to make it work. 
Once that's handled, I think we'll be ready to publish the package on ROS.

**Comment by Stormiix** [comment]
The package is officially indexed and has a wiki entry: http://wiki.ros.org/ping360_sonar

**Comment by tomlogan501** [comment]
Nice !
