### ISSUE TITLE
Unit tests and/or integration tests (with ROS)

### ISSUE THREAD

**Issue by tomlogan501** [CentraleNantesRobotics/ping360_sonar#21]
**Is your feature request related to a problem? Please describe.**
No test, no coverage

**Describe the solution you'd like**
Add test directory and coverage support

**Additional context**
Use of python coverage module ? Does it generate a rapport ?

**Comment by Stormiix** [comment]
Thanks for the bug reports, tests and feature suggestions. Let's add tomlogan501 for his contributions. cc @all-contributors

**Comment by Stormiix** [comment]
@all-contributors please add @tomlogan501 for tests, bugs and features.

**Comment by Stormiix** [comment]
Now that we have CI in place, tests would be an awesome thing to add. If you have any suggestions please do not hesitate!

**Comment by tomlogan501** [comment]
We  could start with simple unit tests for common use verification and then add integration tests with ROS with emulated sensor and/or gazebo.

**Comment by Stormiix** [comment]
Yes definitely. I will try to improve the emulator #33 once I'm done with the #34.

**Comment by tomlogan501** [comment]
What ? It should be reopened
