### ISSUE TITLE
Gazebo

### ISSUE THREAD

**Issue by Stormix** [CentraleNantesRobotics/ping360_sonar#22]
**Is your feature request related to a problem? Please describe.**
TODO
**Describe the solution you'd like**
TODO
**Describe alternatives you've considered**
TODO
**Additional context**
TODO

**Comment by tomlogan501** [comment]
What do you want to create in gazebo ?
An emulation of the sensor ?

**Comment by Hameck** [comment]
@tomlogan501 Yes, that's it, the idea is to be able to generate the information (to emulate the sensor messages) from gazebo, in this way we could test SLAM algorithms using Ping360 from a virtual environment.

**Comment by Stormix** [comment]
Closed as this is not longer needed/wanted

**Comment by tomlogan501** [comment]
What do you propose for ? I still require it for a ROV simulation in Gazebo, not you ?
