### ISSUE TITLE
Random noise for simulated signal

### ISSUE THREAD

**Issue by tomlogan501** [CentraleNantesRobotics/ping360_sonar#33]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add a parameter to generate either random noise (with another parameter fro amplitude) or square shape or both.

**Comment by Stormiix** [comment]
Can you provide examples of the expected results (what would the image output look like?)?

Thanks.

**Comment by tomlogan501** [comment]
An image would look like this.

![image_rnd](https://user-images.githubusercontent.com/56969577/73159456-d2b5b180-40e6-11ea-98c3-bd46c6d377a3.png)

instead of this 

![image](https://user-images.githubusercontent.com/56969577/73159504-e9f49f00-40e6-11ea-8312-d292d49fbcaa.png)

It will be a complement to gazebo testing.

**Comment by Hameck** [comment]
In the develop branch, I've added something to test (it's not completely random, but it is not a circle - which is useful for debugging). I would like to add something related to a perlin noise, but I couldn't find a lib to do so.

**Comment by tomlogan501** [comment]
You have the pseudo code on wikipedia :) https://fr.wikipedia.org/wiki/Bruit_de_Perlin

**Comment by Stormiix** [comment]
Hello @tomlogan501, I heard you tried to push something on the repo but you couldn't.
What you need to do is to push those changes to your forked repo and then create a new pull request, which we can then review and approve.
Also, don't forget to pull the latest changes :D

Thanks in advance! We really appreciate your help!

**Comment by Hameck** [comment]
@tomlogan501 Checkout the branch `perlin_noise`. I've added the perlin noise in the generation of figures, having something very similar to the image you proposed.
![Screenshot from 2020-01-30 15-20-21](https://user-images.githubusercontent.com/14954732/73457836-95665380-4374-11ea-805d-f66d61635147.png)

**Comment by tomlogan501** [comment]
Did you push your branch ?

**Comment by Stormiix** [comment]
@tomlogan501  it's already merged into master, so you can already try it out using the release or master branch :D 
let us know if it's not working.

**Comment by tomlogan501** [comment]
@Stormiix The emulated laserscan works
