### ISSUE TITLE
Docker files for kinetic and melodic

### ISSUE THREAD

**Issue by tomlogan501** [CentraleNantesRobotics/ping360_sonar#38]
**Is your feature request related to a problem? Please describe.**
Not a problem, more like a CI matter.

**Describe the solution you'd like**
A directory with 2 dockerfiles for kinetic and melodic

**Additional context**
I'm used to deploy with every package a dockerfile to check at minima compilation and , if present, tests.
It prevents to keep unstable branches.

**Comment by tomlogan501** [comment]
I have seen that github action is set to melodic; It's nice but could you add kinetic ?

**Comment by Stormiix** [comment]
Yes definetly, I'll add that in a future release.

**Comment by tomlogan501** [comment]
I send to Henrique a patch for this.
