### ISSUE TITLE
Remove roslint from master branch

### ISSUE THREAD

**Issue by tomlogan501** [CentraleNantesRobotics/ping360_sonar#39]
**Is your feature request related to a problem? Please describe.**
In order to reduce number of package needed on an embedded computer, it would be great to remove this dependency on master 

**Describe the solution you'd like**
- Update CMakelist according to git branch

- Update package list with a script ? with github action ?

**Describe alternatives you've considered**
Manual edit each time :(

**Comment by Stormiix** [comment]
I added a CI job #44   that removes roslint from the dependencies and publishes the changes to the "release" branch.

**Comment by tomlogan501** [comment]
Nice !
