### ISSUE TITLE
CI failure

### ISSUE THREAD

**Issue by tomlogan501** [CentraleNantesRobotics/ping360_sonar#50]
**Describe the bug**
Lint step fail for some unknown reason

**To Reproduce**
1. Just push something on a branch

**Expected behavior**
Success or error regarding the code added

**Desktop (please complete the following information):**
 - ROS: both melodic / kinetic CI

**Additional context**
For branch feature_48

**Comment by Stormiix** [comment]
That would probably be cause by some extra/trailing whitespace. Check out the linting guide here : https://github.com/CentraleNantesRobotics/ping360_sonar/blob/master/CONTRIBUTING.md#linting 

If the commits pass locally, they should so on the CI too.

Best regards,
Anas
