### ISSUE TITLE
Feature request: Use RADian instead of GRADian

### ISSUE THREAD

**Issue by tomlogan501** [CentraleNantesRobotics/ping360_sonar#52]
**Describe the bug**
Sector scan doesn't correspond well to the ping viewer

**To Reproduce**
1. Create a launcher with maxAngle = 180
1. Launch it and rqt_gui
1. Observe that the sector scan doesn't equal 180° 

**Expected behavior**
Sector scan equal 180°, center on 0°, same as ping viewer.

**Screenshots**
![180_sonar](https://user-images.githubusercontent.com/56969577/76610898-e5127000-6519-11ea-999f-614bc8577bc2.png)

**Desktop (please complete the following information):**
 - ROS: melodic
 - Version : 1.3.2 (head master)

**Additional context**
Tests done in swimming pool, only angle was modified from example.launch

**Comment by Hameck** [comment]
Dear @tomlogan501 , in order to have a 180° scan, you should use a range of 200 gradians! you can always use the conversion : gradian = degrees*(10/9). Just a reminder : our program uses gradian and not degrees for the angles.

**Comment by tomlogan501** [comment]
Ok I will test again, sorry for the trouble

**Comment by tomlogan501** [comment]
Maybe you should abstract this conversion for the common user, even if you mention it.
The ROS Standard would be radian.
This issue can be change to new feature.
