### ISSUE TITLE
Invalid syntax - process has died (roslaunch launch file)

### ISSUE THREAD

**Issue by kamkow8** [CentraleNantesRobotics/ping360_sonar#60]
I get this message when running example.launch.

auto-starting new master
process[master]: started with pid [6969]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to bc9dbdbc-444a-11eb-a5e9-0800279a33a9
process[rosout-1]: started with pid [6980]
started core service [/rosout]
process[transform_sonar_frame-2]: started with pid [6987]
process[ping360_node-3]: started with pid [6988]
Opening /dev/ttyUSB0 at 115200 bps
Failed to open the given serial port
('\t', SerialException(2, "could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'"))
[ping360_node-3] process has died [pid 6988, exit code 1, cmd /home/kamil/Workspaces/sonar_ws/src/ping360_sonar/nodes/ping360_node __name:=ping360_node __log:=/home/kamil/.ros/log/bc9dbdbc-444a-11eb-a5e9-0800279a33a9/ping360_node-3.log].
log file: /home/kamil/.ros/log/bc9dbdbc-444a-11eb-a5e9-0800279a33a9/ping360_node-3*.log

What I did:
- pip install bluerobotics-ping==0.0.9
- I created the folders: sonar_ws> src
- cd sonar_ws / src
- git clone https://github.com/CentraleNantesRobotics/ping360_sonar.git
- cd ../
- catkin_make
- in launch file: <env name = "emulated_sonar" value = "true" />
- roslaunch ping360_sonar example.launch

I only have such files in the given path:
master.log                   roslaunch-kamil-vb-5449.log  rosout-1-stdout.log
roslaunch-kamil-vb-4884.log  roslaunch-kamil-vb-5491.log  rosout.log
roslaunch-kamil-vb-5116.log  roslaunch-kamil-vb-5529.log  transform_sonar_frame-1-stdout.log

**Comment by Stormix** [comment]
It might be that your sonar is not plugged in to your computer, or is on a different port, try changing the `/dev/ttyUSB0` to the right USB port.

**Comment by Stormix** [comment]
Please reopen if you feel like it's not the case.

**Comment by kamkow8** [comment]
Yes, the sonar is not connected, but I wanted to run an emulator.
However, despite changing false to true in:
<env name = "emulated_sonar" value = "true" />
the emulator does not start. Can it be turned on without connecting a sonar?
