### ISSUE TITLE
Compatibility with Ping360 and ethernet connectivity

### ISSUE THREAD

**Issue by chrstrom** [CentraleNantesRobotics/ping360_sonar#62]
Hi, we are looking into switching out our current sonar for a Ping360. Currently, we are looking into existing libraries/tools to make our lives easier. :smile: We would ideally have all our sensors available over ethernet, so I was wondering how much it would take to move the serial communication used in this library over to ethernet communication.

Alternatively, is ethernet compatibility a planned feature?

**Comment by Hameck** [comment]
@chrstrom With the pandemics, we lost our permission to access our lab, so unfortunately, we can't test modifications with the way we create a connexion with the sensor. However, you can try to create this functionality, I think it would be a great improvement.
