### ISSUE TITLE
Question: range of intensities list in `data` topic

### ISSUE THREAD

**Issue by ssagrawal01** [CentraleNantesRobotics/ping360_sonar#63]
Hi Anas and Henrique,

Question for you about the `data` topic. The list of `intensities`: does the list run from 0 meters up to maximum range, or does it run from sensor minimum range (i.e. 0.75m) to sensor maximum range?

Thank you very much for the helpful package,
Siddharth

**Comment by Stormix** [comment]
Hey Siddharth, 

Actually in the `data` topic, the list of intensities, corresponds to a single range, as you can see in the provided [msg definition](https://github.com/CentraleNantesRobotics/ping360_sonar/blob/master/msg/SonarEcho.msg). The sonar samples the range and for each sample point an intensity is returned.: 

```
  uint8 range      #  range value [m]
  uint8[] intensities    # intensity data [0-255].  This is the actual data received from the sonar
```

Here's an excerpt from our project report, that explains how the sonar works: 
![image](https://user-images.githubusercontent.com/18377687/118324637-95a34780-b502-11eb-83e9-c9cddba24787.png)

Let me know if you have anymore questions.

Anas
