### ISSUE TITLE
error: File "<string>", line 1, in <module> ModuleNotFoundError: No module named 'node'

### ISSUE THREAD

**Issue by tank179** [CentraleNantesRobotics/ping360_sonar#64]
When roslaunch ping360_sonar example.launch is runned with python 3.6, the error is as follows:
Traceback (most recent call last):
  File "/home/tank179/catkin_workspace/src/ping360_sonar/nodes/ping360_node", line 3, in <module>
    from ping360_sonar import main
  File "/home/tank179/catkin_workspace/devel/lib/python2.7/dist-packages/ping360_sonar/__init__.py", line 34, in <module>
    exec(__fh.read())
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'node'

**Comment by tomlogan501** [comment]
with brping=0.0.9 I don't have your issue on develop.
Are you on master ? What python do you use ?

**Comment by tank179** [comment]
Ok. Thank you very much!

**Comment by tank179** [comment]
Could you give me more detailed operation? I am the beginner for ROS. Thank you very much for your help.

**Comment by tomlogan501** [comment]
git checkout develop on the repository
pip install bluerobotics-ping=0.0.9

**Comment by tank179** [comment]
Ok. Many thanks!

**Comment by tank179** [comment]
According to your guide, example.launch can start normally. But there is not image, Rviz interface does not appear. After example.launch runned, the status is as follows:
NODES
  /
    ping360_node (ping360_sonar/ping360_node)
    transform_sonar_frame (tf/static_transform_publisher)

auto-starting new master
process[master]: started with pid [6549]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 4ee6a094-b999-11eb-b6c4-b46921529d97
process[rosout-1]: started with pid [6560]
started core service [/rosout]
process[transform_sonar_frame-2]: started with pid [6567]
process[ping360_node-3]: started with pid [6568]
Opening /dev/ttyUSB0 at 115200 bps
Initialized Sensor: True

Appreciate your help again!

**Comment by tank179** [comment]
Now I have not the sonar, run the emulated sonar, and have set the env variable to "true".

**Comment by tomlogan501** [comment]
Sorry but the scan topic is broken, try to contact the maintainer @Stormix or @Hameck

**Comment by tank179** [comment]
Ok. Thanks.
