### ISSUE TITLE
Rviz cant visualize laser scan

### ISSUE THREAD

**Issue by codeerzz** [CentraleNantesRobotics/ping360_sonar#87]
I am trying to take laser scan data from sonar. Actually i did it but i cant visualize in rvizz.

I tried to change size of laserscan but its not effected.Also sonar_frame selected
![image](https://github.com/CentraleNantesRobotics/ping360_sonar/assets/61847447/c522fd5e-a39b-4cf1-be0b-a36c46062c91)
here echo of laser scan
![image](https://github.com/CentraleNantesRobotics/ping360_sonar/assets/61847447/6139c029-f99d-4061-8902-8405bbb3ab66)

**Comment by AlexisFetet** [comment]
Hi, it seems like you picked the ROS version (your repo is private so I'm not sure)
I saw a [commit](https://github.com/CentraleNantesRobotics/ping360_sonar/commit/0fa74806b89542b7f2e2a64031a7a0908a4b3c95)  in one of our forks mentionning a similar issue, let me know if that solves yours.

**Comment by codeerzz** [comment]
Thanks for your reply. its solved my problem.
