### ISSUE TITLE
ERROR:colcon.colcon_cmake.task.cmake.build

### ISSUE THREAD

**Issue by phamquandung** [CentraleNantesRobotics/ping360_sonar#88]
Hello authors, 

When I tried to build the code, I encountered this issue

**Describe the bug**
It said that: 
Failed to find the following files:
-/home/pqdung/ros2_workspace/install/ping360_sonar_msgs/share/ping360_sonar_msgs/package.sh
**To Reproduce**
1. I run: colcon build --symlink-install --packages-select ping360_sonar in the folder ~/ros2_workspace
2. See error
```
colcon build --symlink-install --packages-select ping360_sonar
Starting >>> ping360_sonar
[0.941s] ERROR:colcon.colcon_cmake.task.cmake.build:Failed to find the following files:
- /home/pqdung/ros2_workspace/install/ping360_sonar_msgs/share/ping360_sonar_msgs/package.sh
Check that the following packages have been built:
- ping360_sonar_msgs
Failed   <<< ping360_sonar [0.06s, exited with code 1]

Summary: 0 packages finished [0.53s]
  1 package failed: ping360_sonar
```

**Screenshots**
![Screenshot from 2023-09-26 11-26-15](https://github.com/CentraleNantesRobotics/ping360_sonar/assets/28943896/855644f1-0ce6-4650-982d-d49861670cf8)

**Desktop (please complete the following information):**
 - ROS: humble
 - Python python 3.10.12
 - Version 3

**Comment by AlexisFetet** [comment]
Hi,

I see you ran `colcon build --symlink-install --packages-select ping360_sonar` which does not build the message package. did you build the message package beforehand? (`colcon build --symlink-install --packages-select ping360_sonar_msgs`)

**Comment by AlexisFetet** [comment]
Hi,

`colcon build --symlink-install --packages-select ping360_sonar` only targets the `ping360_sonar` package and not its dependancies. please run `colcon build --symlink-install --packages-up-to ping360_sonar` to build `ping360_sonar` and its dependancies.
![image](https://github.com/CentraleNantesRobotics/ping360_sonar/assets/94527511/5eb80dfe-8b80-4ce1-b769-836e3fef9d32)
I am closing this issue as I believe this to be solved.
